### ISSUE TITLE
More than one row visible with active on middle

### ISSUE THREAD

**Issue by DiogoBatistaComponto** [josex2r/jQuery-SlotMachine#10]
HI there i'm using you plugin on a project and i would like to know how to achieve a functionality similar to this image where we have more than one row visible. In the middle we have the slot that will be randomised and is the active one.

![screen shot 2015-03-20 at 01 32 45](https://cloud.githubusercontent.com/assets/11074515/6744410/14290d14-cea1-11e4-8332-59a32bbf175d.png)

**Comment by josex2r** [comment]
Hi.
I've not tryed to do that, but I think that you can enlarge the height of the wrapper.

Try to ask to the user of the "issue #9", he posted an image doing that.
