### ISSUE TITLE
Potential Bug?

### ISSUE THREAD

**Issue by PetersonLian** [josex2r/jQuery-SlotMachine#13]
I prefer the following snippet be written into `SlotMachine.prototype.stop` instead of `SlotMachine.prototype.shuffle`  
  
    if (this.futureActive === null) {
      //Get random or custom element
      var rnd = this.getCustom();
      this.futureActive = rnd;
    }
  Don't you think that a destination(`futureActive`)is better specified in stop function rather than start function since the destination(`futureActive`) is used to determine where `spin` should stop at during *STOPPING* phase?  
  Suppose a scenario.At beginning, I create an instance of `SlotMachine` without specify the `randomize` (like following snippet)  
    
            var machine1 = $("#machine1").slotMachine({
		    active	: 0,
		    delay	: 500
	    });
And I start spinning by evoke `machine1.shuffle()`. (It should be spinning non-stop)
Then I start do an AJAX request and in callback function, I know a destination at which the `spin` should stop.
I evoke following sinppet.  

                 machine1.setRandomize(destinationIndex);
                machine1.stop();  
.
If the first aforementioned snippet was written into `SlotMachine.prototype.shuffle`, then `machine1.setRandomize(destinationIndex)` takes no effect.
But instead, I wrote the snippet into `SlotMachine.prototype.shuffle`, It works effectively and the `spin` can stop at whichever index given.

**Comment by yuezk** [comment]
Same issue here.

**Comment by josex2r** [comment]
I'll merge it and publish the new bower version.
