### ISSUE TITLE
Animation improvement

### ISSUE THREAD

**Issue by marcobiedermann** [josex2r/jQuery-SlotMachine#15]
To improve the animation, I recommend using `requestAnimationFrame` instead of `setTimeout`. Also to make the animation a bit smoother, animate it via `transform: translateY()?

**Comment by josex2r** [comment]
Fixed requestAnimationFrame in 093f276d4778fa8a2ad6b5c8065e3d3369230616

**Comment by marcobiedermann** [comment]
:+1: Nice!

**Comment by marcobiedermann** [comment]
What about animating it using `transform: translateY()`? Using `transform` instead of `margin` would reduce the repaint a lot
