### ISSUE TITLE
a little question

### ISSUE THREAD

**Issue by ctf0** [josex2r/jQuery-SlotMachine#17]
hi there, i wanted to ask you if its possible to use the plugin for something like changing numbers, so lets say you have 2 divs 
```html
<div id="number_1" value="1000"><div>
<div id="number_2" value="2500"><div>
```
so now when you scroll down the plugin will check the scroll direction and fire `machine.next()` then spin the number from **1000 > 2500** & same goes when scrolling up, it will fire `machine.prev()` then spin the number from **2500 > 1000**.

**Comment by josex2r** [comment]
I think you can do that.

Maybe using [waypoints](https://github.com/imakewebthings/waypoints) to trigger the next() or prev() functions.
