### ISSUE TITLE
improvement: animate transform instead of margin

### ISSUE THREAD

**Issue by marcobiedermann** [josex2r/jQuery-SlotMachine#18]
Animating other properties besides `opacity` and `transform` cause a lot of repaint. Especially on mobile devices this causes a lot of frame drops.

![slotmaschine](https://cloud.githubusercontent.com/assets/5244986/12979548/33e43c66-d0d8-11e5-9844-def688e1e7c6.png)

Could you change animating `margin-top:` to `transform: translateY()`?

For more information read [High Performance Animations](http://www.html5rocks.com/en/tutorials/speed/high-performance-animations/?redirect_from_locale=de)

**Comment by josex2r** [comment]
The opacity it's made with SVG, don't know if exist other way to improve this effect.

But the margin style can be optimized, but I think it will need a refactor.
I'll think it and if it's possible I'll publish a new release.

**Comment by josex2r** [comment]
Let's get started... 12acf26cf9807533a5a83c5f0639710de67371ce

**Comment by marcobiedermann** [comment]
@josex2r :+1: Nice, thank you Jose!

**Comment by josex2r** [comment]
Hi Marco

It's done in [v3.0.0](https://github.com/josex2r/jQuery-SlotMachine/releases/tag/3.0.0)

The bounce effect has dissapeared but I think it's not important, anyways exist a css file to customize the classes.
