### ISSUE TITLE
on Machine Stop the spinning is getting strucked

### ISSUE THREAD

**Issue by naveen305** [josex2r/jQuery-SlotMachine#21]
on Machine Stop the spinning is getting strucked 

```
        $("#slotMachineButtonStop").click(function(){
                machine4.stop();
                machine5.stop();
                machine6.stop();
            });
```

![strucked](https://cloud.githubusercontent.com/assets/12660060/13554665/ec4dcea8-e3d3-11e5-959c-cd094fa73289.jpg)

**Comment by josex2r** [comment]
Try to upgrade to the new version

**Comment by nullart2** [comment]
im getting this issue with latest version. Im using this for ionic 5. any idea how to solve this?
