### ISSUE TITLE
Add css to active slot while spinning

### ISSUE THREAD

**Issue by platypusmuerte** [josex2r/jQuery-SlotMachine#38]
If the animation is in effect, is there a css class for the tile in the position that becomes active?

Say mine is 3 tiles tall, as it spins I want the one that will become final, to have different css than surrounding tiles.

tile one - class:notactive
tile two - class:active
tile three -class:notactive

Then as it animates, the tile in the middle always has the class:active.

Cannot figure out how to accomplish this.

**Comment by josex2r** [comment]
Use the `active` attribute
