### ISSUE TITLE
no repeat on randomize slotmachine

### ISSUE THREAD

**Issue by anagogomes** [josex2r/jQuery-SlotMachine#45]
Hi, on the slotmachine randomize, how could we make machine results never repeat, between machines?

**Comment by josex2r** [comment]
Hello @anagogomes.
Use the [randomize()](https://github.com/josex2r/jQuery-SlotMachine#settings) function to return the elements that have never appeared, just implement a little cache:

```js
const elements = [];

function randomize() {
  // Get random index
  const index = ...;
  // Check that have never appeared
  if (elements.includes(index)) {
    // Element have appeared, should return a different index
  }
  // Push it to the "cache"
  elements.push(index);
  return index;
}
```

**Comment by anagogomes** [comment]
Thanks a lot!

Ana Gomes
Telem: 919407729
Skype: anagogomes
