### ISSUE TITLE
Isn't jslotmachine.min.js suppose to be slotmachine.min.js?

### ISSUE THREAD

**Issue by Chris-Happy7** [josex2r/jQuery-SlotMachine#48]
I was looking at the documentation, and I saw something that was quite confusing:

> If you preffer jQuery style then import the wrapper after the jQuery library:
> 
> ```
> <script src="/path/to/jquery.min.js"></script>
> <script src="/path/to/jslotmachine.min.js"></script>
> <script src="/path/to/jquery.slotmachine.min.js"></script>
> ```

First, "preffer" has a typo and I think:
`<script src="/path/to/jslotmachine.min.js"></script>`
should be:
`<script src="/path/to/slotmachine.min.js"></script>`

**Comment by josex2r** [comment]
Thanks @Chris-Happy7 !
It should be fixed now on master branch 😄
