### ISSUE TITLE
slotmachine.min.js breaks on Mobile Safari on iOS 9

### ISSUE THREAD

**Issue by J22Melody** [josex2r/jQuery-SlotMachine#49]
```
TypeError: Attempting to change configurable attribute of unconfigurable property.
```

Inspected by Mac, It's an error when `Object.defineProperty` is called. I found two `Object.defineProperty` calls in `slotmachine.min.js`, but I am not sure the exact reason why this only happens on iOS9.

Device version: iOS 9.3.2

**Comment by J22Melody** [comment]
Just found a related bug: https://bugs.webkit.org/show_bug.cgi?id=146774

I can fix this by commenting out this getter: https://github.com/josex2r/jQuery-SlotMachine/blob/master/lib/slot-machine.js#L24

**Comment by josex2r** [comment]
Hello @J22Melody.
Thanks for finding the bug 👍
I'll try to fix the bug asap but if you preffer you can make a pull request

**Comment by J22Melody** [comment]
Hi @josex2r !

My fix is simply removing the getter on this line https://github.com/josex2r/jQuery-SlotMachine/blob/master/lib/slot-machine.js#L24.

I am not sure if this affects other code. If this solution looks good to you, I can make a PR.
