### ISSUE TITLE
Set Stop Position

### ISSUE THREAD

**Issue by Marow** [josex2r/jQuery-SlotMachine#53]
Can i set the Stop Position or something? 

Its already choosed what a user get, i will only set the position of stopping...

**Comment by majimboo** [comment]
+1 need this one too because the randomization is done on the server side.

**Comment by josex2r** [comment]
Hello.
This can be done yet using the `randomize` function.
You can see an example in the source code of the example page ([index.html#L255](https://github.com/josex2r/jQuery-SlotMachine/blob/master/index.html#L255)).

**Comment by richieteh94** [comment]
@Marow if you want to stop at designed position after spun try use changeSettings function . you can see inside the normal slotmachine.js there is a function inside it.  
Example:
`
$("machine1").slotMachine({active:0,delay:500,direction:"down"});
machine1.shuffle(9999999);
machine1.changeSettings({ randomize: function(){return 0;}})
`
