### ISSUE TITLE
Mobile devices stutter animation

### ISSUE THREAD

**Issue by modernmediagrp** [josex2r/jQuery-SlotMachine#6]
Nice work,
I have integrated this into a small project of mine, I am noticing on mobile phone the animation get hung up or freezes. Donyou have any recommendations on how to speed up or smooth the animation for mobile devices?
Thanks

**Comment by madsnedergaardnetbooster** [comment]
What's the status of this issue? I tried the suggested older release, but I got multiple new errors with that version.

**Comment by brain00021** [comment]
THX for your sharing.But I using your plugin .I create two click button (star & stop ) ,when element shuffle animate when will stop motion . I click stop this moment . all element show active 0 element .
Hope you understand my question~

**Comment by Benjaminsson** [comment]
Is there a way to maybe disable some effects in Safari? Noticed some stuttering on both iOS and OSX Safari.

**Comment by niravamodi** [comment]
I have integrated "Randomize your stuff!" slot machine (which is with 3 options) at this url http://josex2r.github.io/jQuery-SlotMachine/.But some how it is not working in Safari. So I have checked your original url (http://josex2r.github.io/jQuery-SlotMachine/) in Safari, that is also not working in Safari. Please Please Please help me to solve that problem. I really need it urgently and ASAP.
