### ISSUE TITLE
Only fixed active-slot when showing multiple rows?

### ISSUE THREAD

**Issue by madsnedergaardnetbooster** [josex2r/jQuery-SlotMachine#9]
Is it possible to get a result, where the active slot is fixed while the next and previous slot is random?
I am using your great plugin on a page, where 3 rows of slots are shown at the same time, but as you can see on the attached image they match on all 3 rows.
![screen shot](https://cloud.githubusercontent.com/assets/6602995/5612524/b16abff0-94d6-11e4-9fe7-aecb7f91efc7.png)

**Comment by josex2r** [comment]
Hi,
Do you mean that the watermelon have to be fixed, and the orange and the "7" are random?
Mess the images in the html:
```
<div>
    <img src="Orange" />
    <img src="Watermelon" />
    <img src="Seven" />
</div>
<div>
    <img src="Seven" />
    <img src="Watermelon" />
    <img src="Orange" />
</div>
```

Or you can change the images dinamically while the machine is spinning

**Comment by madsnedergaardnetbooster** [comment]
You were right, I managed to randomize it by changing background graphics. Thanks :)
